[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GaussianMixtures = "cc18c42c-b769-54ff-9e2a-b28141a64aae"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensorNetworks = "2919e153-833c-4bdc-8836-1ea460a35fc7"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TTNSsketch = "8ea83db9-5ed3-451b-99f7-067dc323b179"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"

[compat]
CSV = "0.10"
CategoricalArrays = "0.10"
DataFrames = "1"
DataStructures = "0.18.22"
Dictionaries = "0.4.2"
Glob = "1.3.1"
GraphRecipes = "0.5, 0.6"
Graphs = "1.9"
ITensorMPS = "0.3"
ITensorNetworks = "0.11.23"
ITensors = "0.7"
JLD2 = "0.5"
MLJBase = "0.21"
NamedGraphs = "0.6.8"
NetworkLayout = "0.4"
Plots = "1"
Random = "1.8"
SimpleTraits = "0.9.4"
SimpleWeightedGraphs = "1.5.0"
XGBoost = "2"
julia = "1"
