name = "TTNSsketch"
uuid = "8ea83db9-5ed3-451b-99f7-067dc323b179"
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ITensorNetworks = "2919e153-833c-4bdc-8836-1ea460a35fc7"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataStructures = "0.18"
Graphs = "1.9"
ITensorNetworks = "0.11"
ITensors = "0.7"
LegendrePolynomials = "0.4"
NamedGraphs = "0.6"
SimpleTraits = "0.9"
SimpleWeightedGraphs = "1.5"
StatsBase = "0.33, 0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
